default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: database
  port: 5432
  database: cad_product_development

development:
  <<: *default

test:
  <<: *default

production:
  url: <%= ENV['DATABASE_URL'] %>
